version: '3'

services:
  letsencrypt:
    build: ./docker
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?required}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?required}
      - EMAIL=${EMAIL:?required}
    volumes:
      - ./${DOMAIN}:/letsencrypt/:rw
    command: bash entrypoint.sh ${DOMAIN:?required}
