version: '3'

services:
  letsencrypt:
    image: dang3r/letsencrypt-route53:1.0.0
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?required}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?required}
    volumes:
      - ./${DOMAIN}:/letsencrypt/:rw
    command: certbot certonly -d ${DOMAIN:?required} --dns-route53 --logs-dir /letsencrypt/ --config-dir /letsencrypt/ --work-dir /letsencrypt/ -m ${EMAIL:?required} --agree-tos --non-interactive
